### ISSUE TITLE
MSRV raised to 1.34.0 in 1.0.10-11

### ISSUE THREAD

**Issue by dekellum** [alexcrichton/flate2-rs#207]
This is minimally just and FYI for maintainers and users, if MSRV bumps such as this in patch releases are considered acceptable here. 

When compiling with rust rustc 1.28.0 (9634041f0 2018-07-30) 1.28.0-x86_64-unknown-linux-gnu:

``` txt
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:96:26
   |
96 |     const ALIGN: usize = std::mem::align_of::<usize>();
   |                          ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:111:41
    |
111 |             .and_then(|i| i.checked_add(std::mem::size_of::<usize>()))
    |                                         ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:388:30
    |
388 |         pub type AllocSize = libc::size_t;
    |                              ^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:47:9
   |
47 |     use std::convert::TryFrom;
   |         ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:109:27
    |
109 |             .and_then(|i| usize::try_from(i).ok())
    |                           ^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors
```

With rust 1.31.0-x86_64-unknown-linux-gnu:

``` txt
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)                                                             
  --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:47:9                                         
   |                                                                                                                                    
47 |     use std::convert::TryFrom;                                                                                                     
   |         ^^^^^^^^^^^^^^^^^^^^^                                                                                                      
                                                                                                                                        
   Compiling parking_lot v0.7.1                                                                                                         
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)                                                             
   --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.11/src/ffi.rs:109:27                                      
    |                                                                                                                                   
109 |             .and_then(|i| usize::try_from(i).ok())                                                                                
    |                           ^^^^^^^^^^^^^^^                                                                                         
```
Where `std::convert::TryFrom` isn't stable until rust 1.34.0.  

If instead I downgrade to 1.0.9, then it compiles with rust 1.28.0 (and possibly lower).

**Comment by alexcrichton** [comment]
Thanks for the report! This crate supports the current stable and last stable for the latest version, so this is intended. If you'd like to send a PR though to build on older versions such a PR is always welcome!
